version: "3"

services:
  play-server:
    build: .
    ports:
      - 9000:9000
      - 5005:5005
    tty: true
#    command: "runWithPostgres"
    command: "runWithMySQL"
    depends_on:
      - postgres-database
      - mysql-database
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/url-shortener"
      - "/opt/url-shortener/target"
      - "/opt/url-shortener/play-server/target"
      - "/opt/url-shortener/project/target"
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgres-database:5432/url-shortener"
      POSTGRES_USER: "urlShortener"
      POSTGRES_PASSWORD: "passw0rd"
      MYSQL_URL: "jdbc:mysql://mysql-database:3306/url-shortener"
      MYSQL_USER: "urlShortener"
      MYSQL_PASSWORD: "passw0rd"

  mysql-database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root-passw0rd"
      MYSQL_DATABASE: "url-shortener"
      MYSQL_USER: "urlShortener"
      MYSQL_PASSWORD: "passw0rd"

  postgres-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "url-shortener"
      POSTGRES_USER: "urlShortener"
      POSTGRES_PASSWORD: "passw0rd"
