version: "3"

services:
  play-server:
    build: .
    ports:
      - 9000:9000
      - 5005:5005
    tty: true
    command: "runWithMySQL"
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/url-shortener"
      - "/opt/url-shortener/target"
      - "/opt/url-shortener/play-server/target"
      - "/opt/url-shortener/project/target"
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgres-database:5432/url-shortener"
      POSTGRES_USER: "urlShortener"
      POSTGRES_PASSWORD: "passw0rd"
      MYSQL_URL: "jdbc:mysql://mysql-database:3306/url-shortener"
      MYSQL_USER: "urlShortener"
      MYSQL_PASSWORD: "passw0rd"
      MONGO_URL: "mongodb://mongo-database:27017/url-shortener"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      ES_HOST: "elasticsearch"
      ES_PORT: "9200"

  mysql-database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root-passw0rd"
      MYSQL_DATABASE: "url-shortener"
      MYSQL_USER: "urlShortener"
      MYSQL_PASSWORD: "passw0rd"
#
#  postgres-database:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: "url-shortener"
#      POSTGRES_USER: "urlShortener"
#      POSTGRES_PASSWORD: "passw0rd"
#
#  redis:
#    image: redis
#    ports:
#      - 6379:6379
#
#  mongo-database:
#    image: mongo
#    ports:
#      - 27017:27017
#
#  elasticsearch:
#    image: elasticsearch:6.6.2
#    ports:
#      - 9200:9200
#      - 9300:9300
