FROM openjdk:8-jdk as buildWorkspace

RUN apt-get update && \
    apt-get install apt-transport-https bc ca-certificates software-properties-common unzip -y

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
    apt-get update && \
    apt-get install sbt -y

WORKDIR /opt/url-shortener

EXPOSE 9000

COPY . .

RUN sbt "playServer/dist" && \
    unzip play-server/target/universal/*.zip && \
    mv play-url-shortener* play-app

FROM openjdk:8-jdk

WORKDIR /opt/url-shortener

COPY --from=buildWorkspace /opt/url-shortener/play-app .

ENTRYPOINT ["/opt/url-shortener/play-app/bin/play-url-shortener"]

