
service: serverless-url-shortener

provider:
  name: aws
  region: ap-southeast-2
  runtime: java8
  vpc:
    securityGroupIds:
      - ${env:SERVERLESS_SECURITY_GROUP}
    subnetIds:
      - ${env:LAMBDA_SUBNET_1}
      - ${env:LAMBDA_SUBNET_2}
      - ${env:LAMBDA_SUBNET_3}
  environment:
    MYSQL_URL: ${env:MYSQL_URL}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}

package:
  artifact: target/scala-2.12/serverless-url-shortener.jar

functions:
  healthCheck:
    handler: com.ruchij.lambda.handlers.HealthCheckHandler
    events:
      - http:
          path: health-check
          method: get

  insertUrl:
    handler: com.ruchij.lambda.handlers.UrlInsertionHandler
    events:
      - http:
          path: url
          method: post

  urlInformation:
    handler: com.ruchij.lambda.handlers.UrlInfoHandler
    events:
      - http:
          path: url/{key}
          method: get
          request:
            parameters:
              paths:
                key: true

  redirectUrl:
    handler: com.ruchij.lambda.handlers.UrlRedirectHandler
    events:
      - http:
          path: redirect/{key}
          method: get
          request:
            parameters:
              paths:
                key: true
