
service: serverless-url-shortener

custom: ${file(./config/config.yml)}

provider:
  name: aws
  region: ap-southeast-2
  runtime: java8
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroup}
    subnetIds:
      - ${self:custom.subnetOne}
      - ${self:custom.subnetTwo}
      - ${self:custom.subnetThree}
  environment:
    MYSQL_URL: ${self:custom.mysqlUrl}
    MYSQL_USER: ${self:custom.mysqlUser}
    MYSQL_PASSWORD: ${self:custom.mysqlPassword}

package:
  artifact: target/scala-2.12/serverless-url-shortener.jar

functions:
  healthCheck:
    handler: com.ruchij.lambda.handlers.HealthCheckHandler
    events:
      - http:
          path: health-check
          method: get

  insertUrl:
    handler: com.ruchij.lambda.handlers.UrlInsertionHandler
    events:
      - http:
          path: url
          method: post

  urlInformation:
    handler: com.ruchij.lambda.handlers.UrlInfoHandler
    events:
      - http:
          path: url/{key}
          method: get
          request:
            parameters:
              paths:
                key: true

  redirectUrl:
    handler: com.ruchij.lambda.handlers.UrlRedirectHandler
    events:
      - http:
          path: redirect/{key}
          method: get
          request:
            parameters:
              paths:
                key: true

  initializeDatabase:
    handler: com.ruchij.lambda.handlers.DatabaseInitializationHandler
    events:
      - http:
          path: init
          method: post
